# General
tab_spaces = 2
hard_tabs = false
max_width = 80
merge_derives = true
force_explicit_abi = true
newline_style = "Auto"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = false
use_small_heuristics = "Default"
use_try_shorthand = false

# Activate unstable features
unstable_features = true
version = "Two"

# Wrap comments
comment_width = 80
wrap_comments = true
normalize_comments = true
